#ifndef HWENTITYH
#define HWENTITYH

typedef enum _STATE {
    ES_ACTIVATED, ES_UNACTIVATED,
    ES_STANDING, ES_WALKING, ES_SKIDDING, ES_STOPPING, ES_RUNNING, ES_FLYING, ES_DUCKING, ES_THROWING,
    ES_JUMPINGUP, ES_JUMPINGDOWN, ES_JUMPATTACK,
    ES_PATROL,
    ES_IDLE, ES_DYING, ES_DEAD, ES_NOTHING
} STATE;

typedef enum _DIRECTION {
    D_RIGHT, D_LEFT
} DIRECTION;

#endif